// process.env.PCB_LAYOUT_WORKERS = '4'
// process.env.PCB_LAYOUT_WORKER_QUEUE_SIZE = '16'
// process.env.PCB_LAYOUT_WORKER_TIMEOUT_MS = '900000'
// process.env.PCB_LAYOUT_WORKER_TERMINATE_TIMEOUT_MS = '10000'

// process.env.PCB_LAYOUT_SUBTREE_WORKERS = '2'
// process.env.PCB_LAYOUT_SUBTREE_MIN_COMPONENTS = '8'
// process.env.PCB_LAYOUT_SUBTREE_WORKER_TIMEOUT_MS = '500000'
// process.env.PCB_LAYOUT_SUBTREE_WORKER_QUEUE_SIZE = '16'
// process.env.PCB_LAYOUT_SUBTREE_WORKER_TERMINATE_TIMEOUT_MS = '5000'

export default process.env;