/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function blockContractVersion(): number

export declare function contractVersion(): number

export declare function evaluateSignalPath(problem: any): any

export declare function passiveIslandContractVersion(): number

export declare function postPlaceScoreContractVersion(): number

export declare function scorePostPlace(problem: any): number

export declare function signalPathBridgeDeltas(problem: any): any

export declare function signalPathContractVersion(): number

export declare function solveBlockPrimitives(problem: any): any

export declare function solveBoardPacked(problem: any): any

export declare function solvePassiveNetIsland(problem: any): any
